version: "3.8"

services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /usr/local/var/mongodb:/data/db
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./backend/chat:/app
      - /app/node_modules
    ports:
      - "3030:3030"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/demo-chat
