version: "3.8"

services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /usr/local/var/mongodb:/data/db
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    links:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/eduAll
      - BASE_URL=http://localhost
    depends_on:
      - db
    volumes:
      - .:/app
